### ISSUE TITLE
Is it able to encrypt full HDD ?

### ISSUE THREAD

**Issue by Abraham313** [redmagnu5/ForbiddenTear#1]
Hi does it able to encrypt full HDD instead of  a specific folder like hidden tears?
Can you  make it  to encrypt Full HDD,Please ? I want to test it in my old laptop.
kind regards

**Comment by redmagnu5** [comment]
Yes, it'll loop through all active drives and directories, and apply encryption recursively.

**Comment by Abraham313** [comment]
Thanks for the information.I have tested it on my laptop.But problem is,It encrypt C drive first  like ( music<pictures<Videos<Download< Desktop) then others drive.Can you  make it others drivers first and desktop last to encrypt ?.I mean It will encrypt Z:\  drive first then (Y,X,W........C:\..... music<pictures<Videos<Download< Desktop ).

Thanks for this educational program.

**Comment by redmagnu5** [comment]
You can change the order under ForbiddenTear/ForbiddenTear/form1.cs. Change it to your needs and recompile.
