### ISSUE TITLE
Very Funny program but have some problem

### ISSUE THREAD

**Issue by classworks** [redmagnu5/ForbiddenTear#2]
I have tested this program and I have  found some issues
1.Shows CMD pop up when execute
2. this is very slow I have only some *.txt file around 5 MB  but it take to encrypt more than 40 min to encrypt !
3. Ransome_note Doesn't appear after encrypted files but It shows after restart. and only remain in C drives (Downloads,Pictures,desktop) folder but It automatically deleted  from other drivers after restart.

4. All Desktop folders  go in hidden mode !
5. Generate 2 Decryptor.exe file in Desktop after restart
Hope you will fix this

**Comment by redmagnu5** [comment]
1. If your intention is to have it run silently/undetected that is beyond the scope of this project. Look into process injection/crypters/packers etc if thats what you intend to do.
2. This will loop through every directory on every drive usable by the system and apply high entropy encryption. That is very resource intensive and there is no way around that. If you want a quicker runtime you can either a: use a more powerful test machine, or b: restrict the directories the encryption runs on. I encourage you to alter the source code to fit your needs.
3. The RANSOM_NOTE.txt is only installed to special folders in the C: drive.
4. Not sure what the case is here, there is no such functionality that does this from this project.
5. Decryptor.exe only installs (once) on special folders in the C drive. You may have had an executable already installed from a previous run.
